{
 "title": "KOMPASS",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Scaling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    { "expr": "count(kube_node_labels)", "legendFormat": "Nodes" },
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\",pod=~\"kompass.*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Spark Driver Pod Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"spark.*driver\",phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"spark.*driver\",phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\",pod=~\"spark.*driver\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Users/Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Average Spark Time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\"} [1m]))",
     "legendFormat": "Spark Execution Time"
    },
    {
     "expr": "1/sum(rate(flask_http_request_total{status=\"200\"}[1m]))",
     "legendFormat": "Seconds per HTTP Request"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container_name!=\"\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}